default:
  stackName: sat-api-legacy

  buckets:
          internal: regen-sat 

  capabilities:
    - CAPABILITY_IAM

  es:
    name: es5
    elasticSearchMapping: 4
    version: 5.3
    instanceCount: 2
    instanceType: m3.medium.elasticsearch
    volumeSize: 80

  apis:
    - name: satellites

  lambdas:
    - name: landsat
      source: 'dist/landsat/'
      handler: index.handler
      timeout: 300
    - name: sentinel
      source: 'dist/sentinel/'
      handler: index.handler
      timeout: 300
    - name: split
      source: 'dist/split/'
      handler: index.handler
      timeout: 300
      envs:
        bucket: '{{buckets.internal}}'
        prefix: '{{stackName}}'
    - name: manager
      source: 'dist/manager/'
      handler: index.handler
      timeout: 300
    - name: api
      source: 'dist/api/'
      handler: index.handler
      timeout: 100
      apiGateway:
        - api: satellites
          path: 'main'
          method: get
        - api: satellites
          path: 'main'
          method: post
          cors: true
        - api: satellites
          path: 'main/count'
          method: get
        - api: satellites
          path: 'main/landsat'
          method: get
        - api: satellites
          path: 'main/landsat'
          method: post
          cors: true
        - api: satellites
          path: 'main/sentinel'
          method: get
        - api: satellites
          path: 'main/sentinel'
          method: post
          cors: true
        - api: satellites
          path: 'main/geojson'
          method: get
        - api: satellites
          path: 'main/geojson'
          method: post
          cors: true
        - api: satellites
          path: 'main/health'
          method: get

production:
  stackName: sat-api-test
